name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: goreleaser/nfpm
    steps:
      - name: Checkout
        uses: actions/checkout@4.2.2

      - name: Build
        run: |
          mkdir out
          nfpm pkg --packager deb --target ./out
          sha256sum -b -- * > ./out/sha256sum.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/out

          
